#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CommonBasicControls.Resource", IsApplication=true)]

namespace CommonBasicControls
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int CourseItems = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int android = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int android_button = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int background = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int image_container = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int sample_0 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int sample_1 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int sample_2 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int sample_3 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int sample_4 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int sample_5 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int sample_6 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int sample_7 = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070035
			public const int analogClock1 = 2131165237;
			
			// aapt resource value: 0x7f070030
			public const int btnCircle = 2131165232;
			
			// aapt resource value: 0x7f070028
			public const int btnCustom = 2131165224;
			
			// aapt resource value: 0x7f070031
			public const int btnDate = 2131165233;
			
			// aapt resource value: 0x7f070025
			public const int btnDefault = 2131165221;
			
			// aapt resource value: 0x7f07003b
			public const int btnNext = 2131165243;
			
			// aapt resource value: 0x7f070011
			public const int btnOK = 2131165201;
			
			// aapt resource value: 0x7f070026
			public const int btnPhoto = 2131165222;
			
			// aapt resource value: 0x7f070027
			public const int btnPosition = 2131165223;
			
			// aapt resource value: 0x7f07002f
			public const int btnPprogress = 2131165231;
			
			// aapt resource value: 0x7f070029
			public const int btnThread = 2131165225;
			
			// aapt resource value: 0x7f070033
			public const int btnTime = 2131165235;
			
			// aapt resource value: 0x7f070014
			public const int button = 2131165204;
			
			// aapt resource value: 0x7f070007
			public const int buttonLogin = 2131165191;
			
			// aapt resource value: 0x7f070013
			public const int buttonOK = 2131165203;
			
			// aapt resource value: 0x7f070037
			public const int cancel = 2131165239;
			
			// aapt resource value: 0x7f07000d
			public const int checkBoxGreen = 2131165197;
			
			// aapt resource value: 0x7f07000c
			public const int checkBoxRed = 2131165196;
			
			// aapt resource value: 0x7f070016
			public const int checkbox = 2131165206;
			
			// aapt resource value: 0x7f070020
			public const int custom = 2131165216;
			
			// aapt resource value: 0x7f070022
			public const int customToastContent = 2131165218;
			
			// aapt resource value: 0x7f07002a
			public const int demo1 = 2131165226;
			
			// aapt resource value: 0x7f07002b
			public const int demo2 = 2131165227;
			
			// aapt resource value: 0x7f07002c
			public const int demo3 = 2131165228;
			
			// aapt resource value: 0x7f07002d
			public const int demo4 = 2131165229;
			
			// aapt resource value: 0x7f07002e
			public const int demo5 = 2131165230;
			
			// aapt resource value: 0x7f070001
			public const int editText1 = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int editText2 = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int editTextPwd = 2131165190;
			
			// aapt resource value: 0x7f070004
			public const int editTextUserName = 2131165188;
			
			// aapt resource value: 0x7f070015
			public const int edittext = 2131165205;
			
			// aapt resource value: 0x7f07001c
			public const int gallery = 2131165212;
			
			// aapt resource value: 0x7f070038
			public const int image1 = 2131165240;
			
			// aapt resource value: 0x7f070039
			public const int image2 = 2131165241;
			
			// aapt resource value: 0x7f07003a
			public const int image3 = 2131165242;
			
			// aapt resource value: 0x7f07003d
			public const int imageView1 = 2131165245;
			
			// aapt resource value: 0x7f070008
			public const int image_container = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int image_view = 2131165193;
			
			// aapt resource value: 0x7f07003f
			public const int item1 = 2131165247;
			
			// aapt resource value: 0x7f07003e
			public const int listView1 = 2131165246;
			
			// aapt resource value: 0x7f07000b
			public const int next_button = 2131165195;
			
			// aapt resource value: 0x7f070036
			public const int ok = 2131165238;
			
			// aapt resource value: 0x7f070023
			public const int picture = 2131165219;
			
			// aapt resource value: 0x7f07001b
			public const int popupButton = 2131165211;
			
			// aapt resource value: 0x7f070024
			public const int prompt = 2131165220;
			
			// aapt resource value: 0x7f070010
			public const int radioButtonFamale = 2131165200;
			
			// aapt resource value: 0x7f07000f
			public const int radioButtonMale = 2131165199;
			
			// aapt resource value: 0x7f07000e
			public const int radioGroupGander = 2131165198;
			
			// aapt resource value: 0x7f070018
			public const int radio_blue = 2131165208;
			
			// aapt resource value: 0x7f070017
			public const int radio_red = 2131165207;
			
			// aapt resource value: 0x7f07001a
			public const int ratingbar = 2131165210;
			
			// aapt resource value: 0x7f07001d
			public const int seekBar1 = 2131165213;
			
			// aapt resource value: 0x7f07001e
			public const int seekBar2 = 2131165214;
			
			// aapt resource value: 0x7f070012
			public const int spinner1 = 2131165202;
			
			// aapt resource value: 0x7f07000a
			public const int status_text = 2131165194;
			
			// aapt resource value: 0x7f070032
			public const int textDateInfo = 2131165234;
			
			// aapt resource value: 0x7f070034
			public const int textTimeInfo = 2131165236;
			
			// aapt resource value: 0x7f070000
			public const int textView1 = 2131165184;
			
			// aapt resource value: 0x7f070005
			public const int textView2 = 2131165189;
			
			// aapt resource value: 0x7f07001f
			public const int textView3 = 2131165215;
			
			// aapt resource value: 0x7f070021
			public const int title = 2131165217;
			
			// aapt resource value: 0x7f070019
			public const int togglebutton = 2131165209;
			
			// aapt resource value: 0x7f070003
			public const int txtResult = 2131165187;
			
			// aapt resource value: 0x7f07003c
			public const int videoView = 2131165244;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Demo01EditText = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Demo02Login = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Demo03MultiResolution = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Demo04CheckBoxRadioButton = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Demo05Spinner = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Demo06SwitchAndRatingBar = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Demo07PopupMenu = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Demo08Gallery = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Demo09SeekBar = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Demo10CustomToast = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Demo10Toast = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Demo11AlertDialog = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Demo12ProgressDialog = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Demo13DatePickerDialog = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int Demo14LinearLayout = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int Demo15GridLayout = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int Demo16TableLayout = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int Demo17RelativeLayout = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int Demo18FrameLayout = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int Demo2002VideoView = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int Demo2003ImageView = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int Main = 2130903061;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int Demo07PopupMenu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int configFile = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int showPopup = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
