#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AdSubApp.Resource", IsApplication=true)]

namespace AdSubApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int CourseItems = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int android = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int android_button = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int app_logo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int background = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int image_container = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int sample_0 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int sample_1 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int sample_2 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int sample_3 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int sample_4 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int sample_5 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int sample_6 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int sample_7 = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int imageView1 = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int listView1 = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int videoView = 2131099650;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ImageView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int VideoView = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int configFile = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int showPopup = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
